### ISSUE TITLE
Adding to Gnome 3 dock

### ISSUE THREAD

**Issue by kinduff** [DonaldChiang/flowdock-electron-app#2]
Hello,

Thanks for putting this together. I use it everyday.

Wanted to post what I did to make it work smooth under Gnome 3, because with the current instructions you will have a missing icon and you will be unable to add it as a favorite.

1. Download the zipfile and extract its contents to the `/opt` folder (you'll need sudo)
2. Changed the name of the folder in `/opt` to "flowdock" to keep things simple
3. Add a desktop entry under `/usr/share/application` called `flowdock.desktop`
4. Add the following content to the file:
```
[Desktop Entry]
Encoding=UTF-8
Name=Flowdock
Exec=/opt/flowdock/Flowdock\ Electron
Terminal=false
Type=Application
Icon=/opt/flowdock/resources/app/static/flowdock.png
Categories=Internet;
StartupWMClass=flowdock electron
```
5. Profit.

To the author: feel free to add this as part of the README, I can do a PR if you want.

**Comment by DonaldChiang** [comment]
Hello, please open a PR and I will update README after merging. Thanks!

**Comment by DonaldChiang** [comment]
README updated, close issue. Thanks!
